export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const APP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const STOCK_ROUTE = '/stock'
export const REACT_APP_API_URL='http://localhost:5000'